# AgeTech Adoption Prediction - Configuration File

# Data Generation Settings
data_generation:
  n_samples: 500
  random_state: 42
  adoption_rate_target: 0.35

# Model Training Settings
model_training:
  test_size: 0.2
  validation_size: 0.2
  cv_folds: 5
  random_state: 42

  # Hyperparameter grids
  xgboost:
    n_estimators: [100, 200, 300]
    max_depth: [3, 5, 7]
    learning_rate: [0.01, 0.1, 0.2]
    subsample: [0.8, 0.9, 1.0]
    colsample_bytree: [0.8, 0.9, 1.0]
    min_child_weight: [1, 3, 5]

  lightgbm:
    n_estimators: [100, 200, 300]
    max_depth: [3, 5, 7]
    learning_rate: [0.01, 0.1, 0.2]
    subsample: [0.8, 0.9, 1.0]
    colsample_bytree: [0.8, 0.9, 1.0]
    min_child_samples: [10, 20, 30]

  random_forest:
    n_estimators: [100, 200, 300]
    max_depth: [5, 10, 15, null]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
    max_features: ["sqrt", "log2", null]

  gradient_boosting:
    n_estimators: [100, 200, 300]
    max_depth: [3, 5, 7]
    learning_rate: [0.01, 0.1, 0.2]
    subsample: [0.8, 0.9, 1.0]

  logistic_regression:
    C: [0.1, 1.0, 10.0, 100.0]
    penalty: ["l1", "l2"]
    solver: ["liblinear", "saga"]

# Feature Engineering Settings
feature_engineering:
  # Technology readiness scoring
  tech_readiness_weights:
    digital_literacy: 1.0
    internet_access: 1.0
    attitude_toward_technology: 1.0
    previous_tech_use: 1.0
    willingness_new_tech: 1.0

  # Health risk scoring
  health_risk_weights:
    cognitive_status: 1.0
    physical_mobility: 1.0
    hearing_vision_impairment: 1.0
    chronic_conditions: 1.0

  # Social support scoring
  social_support_weights:
    caregiver_support: 1.0
    social_engagement: 1.0
    tech_assistance_availability: 1.0

# Performance Targets
performance_targets:
  min_f1_score: 0.85
  min_precision: 0.90
  min_recall: 0.85
  min_auc_roc: 0.85

# File Paths
paths:
  data_raw: "data/raw"
  data_processed: "data/processed"
  models: "models"
  results: "results"
  notebooks: "notebooks"

# Ethical Considerations
ethics:
  fairness_metrics:
    - demographic_parity
    - equalized_odds
    - equal_opportunity

  protected_attributes:
    - age_group
    - socioeconomic_status

  bias_threshold: 0.1

# Visualization Settings
visualization:
  figure_size: [12, 8]
  dpi: 300
  color_palette: "husl"
  style: "seaborn-v0_8"

# Logging Settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/agetch_pipeline.log"
